### ISSUE TITLE
SyntaxError in audio.py?

### ISSUE THREAD

**Issue by dgiglio** [bbye98/minim#21]
Dear Mr. Ye
I inform you that I started experimenting with your project (very interesting, congratulations) and I tumbled into this error:

````
Traceback (most recent call last):
  File "/home/daniele/devel/proj/minim/src/main.py", line 5, in <module>
    from minim import tidal
  File "/home/daniele/devel/proj/minim/src/minim/__init__.py", line 65, in <module>
    from . import audio, discogs, itunes, qobuz, spotify, tidal, utility  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniele/devel/proj/minim/src/minim/audio.py", line 29
    if (FOUND_PILLOW = find_spec("PIL") is not None):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
````
I use python3.11

Best regards

**Comment by bbye98** [comment]
Whoops! Missed a colon. Try pulling the latest commit--it should resolve the issue.
